product_name=input("enter the product_name:")
stock=int(input("enter the stock :"))
price=float(input("enter the price :"))
ram=eval(input("enter the aval sizes:"))
reviews=eval(input("enter the reviews:"))
payment_mode=eval(input("enter the payment_mode"))
brand=eval(input("enter the brand details:"))

print(f"product Name:{product_name}")
print(f"stock:{stock}")
print(f"price: ${price}")
print(f"ram:{ram}")
print(f"reviews:{Reviews}")
print(f"payment mode options:{payment_mode}")
print(f"brand:{brand}")
