CustomerName= input("Name: ")
CustomerAge= int(input("Age: "))
ProductPrice= float(input("Price: "))
ItemsPurchased= eval(input("Items: "))
UniqueCoupon= eval(input("Coupons: "))
DeliveryAddress= eval(input("Address: "))
OrderDetails= eval(input("Order: "))

print(f"Customer Name: {CustomerName}")
print(f"Customer Age: {CustomerAge}")
print(f"Product Price: {ProductPrice}")
print(f"Items Purchased: {ItemsPurchased}")
print(f"Unique Coupon: {UniqueCoupon}")
print(f"Delivery Address: {DeliveryAddress}")
print(f"Order Details: {OrderDetails}")
